"""relax url uniqueness constraints

Revision ID: bf90b856964a
Revises: b45fca6b265b
Create Date: 2026-07-29 22:58:29.737550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf90b856964a'
down_revision: Union[str, Sequence[str], None] = 'b45fca6b265b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_key', table_name='urls')
    op.drop_index(op.f('ix_urls_value'), table_name='urls')
    op.create_index(op.f('ix_urls_value'), 'urls', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_value'), table_name='urls')
    op.create_index(op.f('ix_urls_value'), 'urls', ['value'], unique=True)
    op.create_index('uq_user_key', 'urls', ['key', 'user_id'], unique=True)
    # ### end Alembic commands ###
