"""Create Url model

Revision ID: b45fca6b265b
Revises: 867a8c85b14d
Create Date: 2026-06-15 15:28:13.701716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45fca6b265b'
down_revision: Union[str, Sequence[str], None] = '867a8c85b14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.create_index(op.f('ix_urls_key'), 'urls', ['key'], unique=True)
    op.create_index(op.f('ix_urls_user_id'), 'urls', ['user_id'], unique=False)
    op.create_index(op.f('ix_urls_value'), 'urls', ['value'], unique=True)
    op.create_index('uq_user_key', 'urls', ['key', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_key', table_name='urls')
    op.drop_index(op.f('ix_urls_value'), table_name='urls')
    op.drop_index(op.f('ix_urls_user_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_key'), table_name='urls')
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
